<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\CommentController:commentDelete' => function () {
    return ($this->privates['service_locator.4UObkcl'] ?? $this->load('getServiceLocator_4UObkclService.php'));
}, 'App\\Controller\\CommentController:commentOffense' => function () {
    return ($this->privates['service_locator.vDGjdQG'] ?? $this->load('getServiceLocator_VDGjdQGService.php'));
}, 'App\\Controller\\CommentController:commentUserOnTravel' => function () {
    return ($this->privates['service_locator.4UObkcl'] ?? $this->load('getServiceLocator_4UObkclService.php'));
}, 'App\\Controller\\PmController:addPm' => function () {
    return ($this->privates['service_locator.Tgh4rjm'] ?? $this->load('getServiceLocator_Tgh4rjmService.php'));
}, 'App\\Controller\\QuestionController:questionTravel' => function () {
    return ($this->privates['service_locator.r5iLDWN'] ?? $this->load('getServiceLocator_R5iLDWNService.php'));
}, 'App\\Controller\\TravelController:travelAdd' => function () {
    return ($this->privates['service_locator.XmJoKHR'] ?? $this->load('getServiceLocator_XmJoKHRService.php'));
}, 'App\\Controller\\TravelController:travelHome' => function () {
    return ($this->privates['service_locator.gMOsWdV'] ?? $this->load('getServiceLocator_GMOsWdVService.php'));
}, 'App\\Controller\\TravelController:travelParticipate' => function () {
    return ($this->privates['service_locator.XmJoKHR'] ?? $this->load('getServiceLocator_XmJoKHRService.php'));
}, 'App\\Controller\\TravelController:travelRemove' => function () {
    return ($this->privates['service_locator.XmJoKHR'] ?? $this->load('getServiceLocator_XmJoKHRService.php'));
}, 'App\\Controller\\TravelController:travelSearch' => function () {
    return ($this->privates['service_locator.XmJoKHR'] ?? $this->load('getServiceLocator_XmJoKHRService.php'));
}, 'App\\Controller\\UserController:login' => function () {
    return ($this->privates['service_locator.6UvSqJP'] ?? $this->load('getServiceLocator_6UvSqJPService.php'));
}, 'App\\Controller\\UserController:profilUser' => function () {
    return ($this->privates['service_locator.5KlkkM6'] ?? $this->load('getServiceLocator_5KlkkM6Service.php'));
}, 'App\\Controller\\UserController:registerUser' => function () {
    return ($this->privates['service_locator.P1xQlof'] ?? $this->load('getServiceLocator_P1xQlofService.php'));
}, 'App\\Controller\\UserController:tokenCheck' => function () {
    return ($this->privates['service_locator.5KlkkM6'] ?? $this->load('getServiceLocator_5KlkkM6Service.php'));
}, 'App\\Controller\\CommentController::commentDelete' => function () {
    return ($this->privates['service_locator.4UObkcl'] ?? $this->load('getServiceLocator_4UObkclService.php'));
}, 'App\\Controller\\CommentController::commentOffense' => function () {
    return ($this->privates['service_locator.vDGjdQG'] ?? $this->load('getServiceLocator_VDGjdQGService.php'));
}, 'App\\Controller\\CommentController::commentUserOnTravel' => function () {
    return ($this->privates['service_locator.4UObkcl'] ?? $this->load('getServiceLocator_4UObkclService.php'));
}, 'App\\Controller\\PmController::addPm' => function () {
    return ($this->privates['service_locator.Tgh4rjm'] ?? $this->load('getServiceLocator_Tgh4rjmService.php'));
}, 'App\\Controller\\QuestionController::questionTravel' => function () {
    return ($this->privates['service_locator.r5iLDWN'] ?? $this->load('getServiceLocator_R5iLDWNService.php'));
}, 'App\\Controller\\TravelController::travelAdd' => function () {
    return ($this->privates['service_locator.XmJoKHR'] ?? $this->load('getServiceLocator_XmJoKHRService.php'));
}, 'App\\Controller\\TravelController::travelHome' => function () {
    return ($this->privates['service_locator.gMOsWdV'] ?? $this->load('getServiceLocator_GMOsWdVService.php'));
}, 'App\\Controller\\TravelController::travelParticipate' => function () {
    return ($this->privates['service_locator.XmJoKHR'] ?? $this->load('getServiceLocator_XmJoKHRService.php'));
}, 'App\\Controller\\TravelController::travelRemove' => function () {
    return ($this->privates['service_locator.XmJoKHR'] ?? $this->load('getServiceLocator_XmJoKHRService.php'));
}, 'App\\Controller\\TravelController::travelSearch' => function () {
    return ($this->privates['service_locator.XmJoKHR'] ?? $this->load('getServiceLocator_XmJoKHRService.php'));
}, 'App\\Controller\\UserController::login' => function () {
    return ($this->privates['service_locator.6UvSqJP'] ?? $this->load('getServiceLocator_6UvSqJPService.php'));
}, 'App\\Controller\\UserController::profilUser' => function () {
    return ($this->privates['service_locator.5KlkkM6'] ?? $this->load('getServiceLocator_5KlkkM6Service.php'));
}, 'App\\Controller\\UserController::registerUser' => function () {
    return ($this->privates['service_locator.P1xQlof'] ?? $this->load('getServiceLocator_P1xQlofService.php'));
}, 'App\\Controller\\UserController::tokenCheck' => function () {
    return ($this->privates['service_locator.5KlkkM6'] ?? $this->load('getServiceLocator_5KlkkM6Service.php'));
})));
