<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.gMOsWdV' shared service.

return $this->privates['service_locator.gMOsWdV'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('authenticationUtils' => function () {
    return ($this->services['security.authentication_utils'] ?? $this->load('getSecurity_AuthenticationUtilsService.php'));
}, 'em' => function () {
    return ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php'));
}));
