<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVMZezsd\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVMZezsd/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVMZezsd.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVMZezsd\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerVMZezsd\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'VMZezsd',
    'container.build_id' => 'b22d3c71',
    'container.build_time' => 1524485730,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerVMZezsd');
