<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKOzZmQL\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKOzZmQL/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKOzZmQL.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKOzZmQL\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerKOzZmQL\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'KOzZmQL',
    'container.build_id' => '15303c14',
    'container.build_time' => 1523870244,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKOzZmQL');
