<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCfozrpE\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCfozrpE/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCfozrpE.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCfozrpE\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerCfozrpE\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'CfozrpE',
    'container.build_id' => '8cc1e9b8',
    'container.build_time' => 1525444530,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerCfozrpE');
